// Permission constants for role-based access control
export const PERMISSIONS = {
  // Dashboard permissions
  READ_DASHBOARD: 'READ_DASHBOARD',
  
  // Property permissions
  READ_PROPERTIES: 'READ_PROPERTIES',
  CREATE_PROPERTIES: 'CREATE_PROPERTIES',
  UPDATE_PROPERTIES: 'UPDATE_PROPERTIES',
  DELETE_PROPERTIES: 'DELETE_PROPERTIES',
  
  // Tenant permissions
  READ_TENANTS: 'READ_TENANTS',
  CREATE_TENANTS: 'CREATE_TENANTS',
  UPDATE_TENANTS: 'UPDATE_TENANTS',
  DELETE_TENANTS: 'DELETE_TENANTS',
  
  // Lease permissions
  READ_LEASES: 'READ_LEASES',
  CREATE_LEASES: 'CREATE_LEASES',
  UPDATE_LEASES: 'UPDATE_LEASES',
  DELETE_LEASES: 'DELETE_LEASES',
  
  // Expense permissions
  READ_EXPENSES: 'READ_EXPENSES',
  CREATE_EXPENSES: 'CREATE_EXPENSES',
  UPDATE_EXPENSES: 'UPDATE_EXPENSES',
  DELETE_EXPENSES: 'DELETE_EXPENSES',
  
  // Maintenance permissions
  READ_MAINTENANCE: 'READ_MAINTENANCE',
  CREATE_MAINTENANCE: 'CREATE_MAINTENANCE',
  UPDATE_MAINTENANCE: 'UPDATE_MAINTENANCE',
  DELETE_MAINTENANCE: 'DELETE_MAINTENANCE',
  
  // Reminder permissions
  READ_REMINDERS: 'READ_REMINDERS',
  CREATE_REMINDERS: 'CREATE_REMINDERS',
  UPDATE_REMINDERS: 'UPDATE_REMINDERS',
  DELETE_REMINDERS: 'DELETE_REMINDERS',
  
  // Payment permissions
  READ_PAYMENTS: 'READ_PAYMENTS',
  CREATE_PAYMENTS: 'CREATE_PAYMENTS',
  UPDATE_PAYMENTS: 'UPDATE_PAYMENTS',
  DELETE_PAYMENTS: 'DELETE_PAYMENTS',
  
  // Organization management permissions
  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
  INVITE_USERS: 'INVITE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_ASSIGNMENTS: 'MANAGE_ASSIGNMENTS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  
  // User management permissions
  READ_USERS: 'READ_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  DELETE_USERS: 'DELETE_USERS',
} as const;

// Role constants
export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COORDINATOR: 'COORDINATOR',
  VIEWER: 'VIEWER',
} as const;

// Role levels for hierarchy
export const ROLE_LEVELS = {
  [ROLES.OWNER]: 100,
  [ROLES.ADMIN]: 80,
  [ROLES.MANAGER]: 60,
  [ROLES.COORDINATOR]: 40,
  [ROLES.VIEWER]: 20,
} as const;

// Organization types
export const ORGANIZATION_TYPES = {
  INDIVIDUAL: 'INDIVIDUAL',
  BUSINESS: 'BUSINESS',
  ENTERPRISE: 'ENTERPRISE',
} as const;

export type Permission = keyof typeof PERMISSIONS;
export type RoleName = keyof typeof ROLES;
export type OrganizationType = keyof typeof ORGANIZATION_TYPES;
